name: Android Build Development

on:
  push:
    branches: [ main]

jobs:
    build-android:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: 11
                distribution: 'adopt'

            - name: Install Deps
              run: npm install

            - name: Build Android
              run: cd android && ./gradlew assembleRelease
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: android-app
                path: android/app/build/outputs/apk/release/app-release.apk